### ISSUE TITLE
Entry point not found

### ISSUE THREAD

**Issue by rajada1** [morsisko/xFindOut#4]
After installation I get the following error.
And the plugin is not available

error in english: 
Entry point not found
Could not find GetContextData procedure entry point in dynamic link library C:....

![image](https://user-images.githubusercontent.com/39280362/159102730-32e62cdf-e065-4158-be19-1df8a93f6d6b.png)

**Comment by morsisko** [comment]
What is your version of x32dbg? Is it from 19-10-2020?

**Comment by rajada1** [comment]
> What is your version of x32dbg? Is it from 19-10-2020?

yes

**Comment by morsisko** [comment]
Try to download the newest one, or at least newer than 19 Nov, 2020

**Comment by rajada1** [comment]
It worked with
snapshot_2022-03-21_14-08
Thanks !
